version: '3'

services:
  db:
    build: 
      context: mysql
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysqldb:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - nodenet
    ports:
      - "3306:3306"
  
  app:
    container_name: app
    networks: 
      - nodenet
    build: 
      context: node
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "3000:3000"
    depends_on:
     - db

  nginx:
    container_name: nginx
    networks: 
      - nodenet
    build: 
      context: nginx
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - app
    
networks:
  nodenet:
    driver: bridge